/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_hotel;

/**
 *
 * @author PC Acer
 */


import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import javax.swing.JOptionPane;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;




public class tampilan extends javax.swing.JFrame {
    public String Kelas  = "";
    public int harga;
    Statement stat = null;
    Connection conn = null;
     PreparedStatement pst = null;
    ResultSet rs = null;
   

public void theQuery(){
    
}
    
public tampilan() throws SQLException {
        initComponents();
        kelas.addItem("-- Kelas Kamar --");
        kelas.addItem("Single Bed");
        kelas.addItem("Double Bed");
        conn = (Connection)konek.getkoneksi();
    }
   
   
public void viewData(){
    
    
      info.setText(info.getText()+
                    "\nNama Tamu     : " + nama.getText()+"\n" +
                    "Alamat               : " + alamat.getText()+"\n"+
                    "No.HP                : " + hp.getText()+"\n"+
                    "Kode Kamar     : " + kode.getText()+"\n"+
                    "Kelas Kamar    : " + kelas.getSelectedItem()+"\n"+
                    "Kode Transaksi  : "+kode_transaksi.getText()+"\n" +
                    "Total Bayar        : " + tarif.getText()+"\n");
  
}    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        hp = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        tarif = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        kelas = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        kode_transaksi = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Pengunjung Hotel");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Nama              :");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Alamat            :");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("No. HP              :");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Kode Kamar     :");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Kelas Kamar     :");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Total                   :");

        nama.setText("  ");
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        alamat.setText("  ");

        hp.setText("  ");

        kode.setText("  ");
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        tarif.setText("  ");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        info.setColumns(20);
        info.setRows(5);
        jScrollPane1.setViewportView(info);

        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Kode Transaksi :");

        kode_transaksi.setText("  ");

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        select.setText("Search");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kelas, 0, 135, Short.MAX_VALUE)
                            .addComponent(kode_transaksi)
                            .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(hp, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(alamat)
                            .addComponent(nama))))
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tarif))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(delete)
                    .addComponent(reset)
                    .addComponent(save)
                    .addComponent(update)
                    .addComponent(select))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
     Kelas = (String)kelas.getSelectedItem();
     if (kelas.getSelectedItem() == "Single Bed"){
         harga = 350000;
     }else if (kelas.getSelectedItem() == "Double Bed"){
         harga = 400000;
     }
     tarif.setText(""+harga);
    }//GEN-LAST:event_kelasActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String tht = "DELETE FROM tamu_has_transaksi WHERE tamu_nama =?";
        String thk = "DELETE FROM tamu_has_kamar WHERE tamu_nama =?";
        String transaksi = "DELETE FROM transaksi WHERE kode_transaksi =?";  
        String kamar = "DELETE FROM kamar WHERE kode =?"; 
        String tamu = "DELETE FROM tamu WHERE nama =?";
        try{
        
        pst = conn.prepareStatement(tht);
        pst.setString(1, nama.getText());
        pst.executeUpdate();
        
        pst = conn.prepareStatement(thk);
        pst.setString(1, nama.getText());
        pst.executeUpdate();
         
        PreparedStatement b = conn.prepareStatement(transaksi);
        b.setString(1, kode_transaksi.getText());
        b.executeUpdate();
        
        pst = conn.prepareStatement(kamar);
        pst.setString(1, kode.getText());
        pst.executeUpdate();
       
       pst = conn.prepareStatement(tamu);
        pst.setString(1, nama.getText());
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Berhasil dihapus");
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Gagal menghapus data");}          
            
    }//GEN-LAST:event_deleteActionPerformed
    
            
            
    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
       
    }//GEN-LAST:event_deleteMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        nama.setText("");
        alamat.setText("");
        hp.setText("");
        kode.setText("");
        kode_transaksi.setText("");
        tarif.setText("");
        info.setText("");
    }//GEN-LAST:event_resetMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
     
    }//GEN-LAST:event_resetActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String tamu = "INSERT INTO tamu(tamu_nama,alamat,no_hp) VALUE (?,?,?)";
        String kamar = "INSERT INTO kamar(kamar_kode,kelas,tarif) VALUE (?,?,?)";
        String thk = "INSERT INTO tamu_has_kamar(tamu_nama, kamar_kode) VALUE (?,?)";
        String transaksi = "INSERT INTO transaksi(kode_transaksi,kamar_kode,tamu_nama) VALUE (?,?,?)";
        String tht = "INSERT INTO tamu_has_transaksi(tamu_nama, kode_transaksi) VALUE (?,?)";

        try{
            pst = conn.prepareStatement(tamu);
            pst.setString(1, nama.getText());
            pst.setString(2, alamat.getText());
            pst.setString(3, hp.getText());
            pst.execute();

            pst = conn.prepareStatement(kamar);
            pst.setString(1, kode.getText());
            String value = kelas.getSelectedItem().toString();
            pst.setString(2, value);
            pst.setString(3, tarif.getText());
            pst.execute();

            pst = conn.prepareStatement(thk);
            pst.setString(1, nama.getText());
            pst.setString(2, kode.getText());
            pst.execute();
            
            pst = conn.prepareStatement(transaksi);
            pst.setString(1, kode_transaksi.getText());
            pst.setString(2, kode.getText());
            pst.setString(3, nama.getText());
            pst.execute();
        
            pst = conn.prepareStatement(tht);
            pst.setString(1, nama.getText());
            pst.setString(2, kode_transaksi.getText());
            pst.execute();


          
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data");
        }viewData();

    }//GEN-LAST:event_saveActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked

    }//GEN-LAST:event_saveMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      
      try{
          String tht = "UPDATE tamu_has_transaksi set kode_transaksi=? WHERE tamu_nama=?";
          pst = conn.prepareStatement(tht);
          pst.setString(1, kode_transaksi.getText());
          pst.setString(2, nama.getText());
          pst.executeUpdate();
          
          String thk = "UPDATE tamu_has_kamar set kamar_kode=? WHERE tamu_nama=?";
          pst = conn.prepareStatement(thk);
          pst.setString(1, kode.getText());
          pst.setString(2, nama.getText());
          pst.executeUpdate();
          
          String transaksi = "UPDATE transaksi set kamar_kode=? WHERE kode_transaksi=?";
          pst = conn.prepareStatement(transaksi);
          pst.setString(1, kode_transaksi.getText());
          pst.setString(2, nama.getText());
          pst.executeUpdate();
          
          String kamar = "UPDATE kamar set kelas=?, tarif=? WHERE kamar_kode=?"; 
          pst = conn.prepareStatement(kamar);
          pst.setString(1, kode.getText());
          String v = kelas.getSelectedItem().toString();
          pst.setString(2, v);
          pst.setString(3, tarif.getText());
          pst.executeUpdate();
          
          String tamu = "UPDATE tamu set alamat=?, no_hp=? WHERE tamu_nama=?";
          pst = conn.prepareStatement(tamu);
          pst.setString(1, nama.getText());
          pst.setString(2, alamat.getText());
          pst.setString(3, hp.getText());
          pst.executeUpdate();
          
      
          JOptionPane.showMessageDialog(this, "Berhasil update");
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Gagal update data");
      }viewData();
    }//GEN-LAST:event_updateActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed

        try{
            String tamu = "select * from tamu where nama =?";
            pst = conn.prepareStatement(tamu);
            pst.setString(1, nama.getText()); 
            pst.execute();
            
            String kamar = "select * from kamar where kode=?";
            pst = conn.prepareStatement(kamar);
            pst.setString(1, kode.getText());
            pst.execute();
            
             String transaksi = "select * from transaksi where kode_transaksi=?";
            pst = conn.prepareStatement(transaksi); 
            pst.setString(1, kode_transaksi.getText());
            pst.execute();
              JOptionPane.showMessageDialog(this, "Data ditemukan");
             
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Data tidak tersedia");
      }    
   //   viewData();
        
     
        
    }//GEN-LAST:event_selectActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new tampilan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(tampilan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
       
        });
    }
    
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JTextField hp;
    private javax.swing.JTextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kelas;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField kode_transaksi;
    private javax.swing.JTextField nama;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JButton select;
    private javax.swing.JLabel tarif;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
